// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketFaker.API.Data;

#nullable disable

namespace TicketFaker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241002145616_TicketsSeeding")]
    partial class TicketsSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketFaker.API.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Asiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoQR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puerta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dirección 1, Ciudad 62",
                            Asiento = "Asiento 74",
                            CodigoQR = "79f12362-d68c-4a13-9754-b25cfbde3d71",
                            Description = "Descripción del partido 1",
                            EventDate = new DateTime(2025, 8, 14, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(3897),
                            Fila = "Fila 40",
                            GameName = "Partido 1: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Dirección 2, Ciudad 61",
                            Asiento = "Asiento 99",
                            CodigoQR = "b44f7964-841d-42eb-bd80-b58e42265fc6",
                            Description = "Descripción del partido 2",
                            EventDate = new DateTime(2025, 2, 2, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(3932),
                            Fila = "Fila 9",
                            GameName = "Partido 2: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Dirección 3, Ciudad 48",
                            Asiento = "Asiento 15",
                            CodigoQR = "4ae8ae37-0366-4f76-acb9-2ccec33222ca",
                            Description = "Descripción del partido 3",
                            EventDate = new DateTime(2025, 3, 2, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(3939),
                            Fila = "Fila 46",
                            GameName = "Partido 3: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Dirección 4, Ciudad 81",
                            Asiento = "Asiento 63",
                            CodigoQR = "68ba4405-56d9-498b-b785-c2e8ee579a21",
                            Description = "Descripción del partido 4",
                            EventDate = new DateTime(2025, 9, 3, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(3946),
                            Fila = "Fila 46",
                            GameName = "Partido 4: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Dirección 5, Ciudad 18",
                            Asiento = "Asiento 28",
                            CodigoQR = "2930166f-0ab1-44fc-a334-2d000fc74b96",
                            Description = "Descripción del partido 5",
                            EventDate = new DateTime(2025, 1, 21, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(3954),
                            Fila = "Fila 46",
                            GameName = "Partido 5: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Dirección 6, Ciudad 14",
                            Asiento = "Asiento 73",
                            CodigoQR = "43eb1791-9b81-4bdd-a6f4-1cde93a7f979",
                            Description = "Descripción del partido 6",
                            EventDate = new DateTime(2025, 1, 9, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(3960),
                            Fila = "Fila 40",
                            GameName = "Partido 6: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Dirección 7, Ciudad 89",
                            Asiento = "Asiento 71",
                            CodigoQR = "b869f43b-3938-454d-b0e4-453877939002",
                            Description = "Descripción del partido 7",
                            EventDate = new DateTime(2024, 12, 8, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(3978),
                            Fila = "Fila 14",
                            GameName = "Partido 7: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Dirección 8, Ciudad 5",
                            Asiento = "Asiento 23",
                            CodigoQR = "03095045-47b3-4815-92e0-2496c98c8d2d",
                            Description = "Descripción del partido 8",
                            EventDate = new DateTime(2025, 4, 22, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(3985),
                            Fila = "Fila 45",
                            GameName = "Partido 8: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Dirección 9, Ciudad 65",
                            Asiento = "Asiento 65",
                            CodigoQR = "fadf1496-f4e4-4bf0-8d61-0b3be4eb28bd",
                            Description = "Descripción del partido 9",
                            EventDate = new DateTime(2025, 1, 8, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(3992),
                            Fila = "Fila 7",
                            GameName = "Partido 9: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Dirección 10, Ciudad 10",
                            Asiento = "Asiento 27",
                            CodigoQR = "23127841-4299-4992-a10b-3ec4a4711054",
                            Description = "Descripción del partido 10",
                            EventDate = new DateTime(2024, 10, 4, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4000),
                            Fila = "Fila 48",
                            GameName = "Partido 10: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Dirección 11, Ciudad 78",
                            Asiento = "Asiento 74",
                            CodigoQR = "07008012-9cea-445e-825d-cc801ea8e3c4",
                            Description = "Descripción del partido 11",
                            EventDate = new DateTime(2025, 7, 13, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4007),
                            Fila = "Fila 26",
                            GameName = "Partido 11: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Dirección 12, Ciudad 35",
                            Asiento = "Asiento 86",
                            CodigoQR = "30d9cb5c-4294-4283-879d-4813075de352",
                            Description = "Descripción del partido 12",
                            EventDate = new DateTime(2025, 3, 28, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4028),
                            Fila = "Fila 2",
                            GameName = "Partido 12: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Dirección 13, Ciudad 96",
                            Asiento = "Asiento 4",
                            CodigoQR = "d581ec65-c86a-434a-9965-7a2d8b911f35",
                            Description = "Descripción del partido 13",
                            EventDate = new DateTime(2025, 5, 31, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4036),
                            Fila = "Fila 36",
                            GameName = "Partido 13: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Dirección 14, Ciudad 67",
                            Asiento = "Asiento 77",
                            CodigoQR = "0ee97bf0-e7b0-4252-a62d-591d92917e90",
                            Description = "Descripción del partido 14",
                            EventDate = new DateTime(2025, 7, 5, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4043),
                            Fila = "Fila 46",
                            GameName = "Partido 14: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Dirección 15, Ciudad 49",
                            Asiento = "Asiento 3",
                            CodigoQR = "06843859-9004-471a-9b6e-54b389650d6f",
                            Description = "Descripción del partido 15",
                            EventDate = new DateTime(2025, 2, 24, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4080),
                            Fila = "Fila 24",
                            GameName = "Partido 15: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Dirección 16, Ciudad 65",
                            Asiento = "Asiento 45",
                            CodigoQR = "36b1670e-f8a4-43de-b42e-b0a5342c7763",
                            Description = "Descripción del partido 16",
                            EventDate = new DateTime(2025, 7, 31, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4087),
                            Fila = "Fila 36",
                            GameName = "Partido 16: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 1"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Dirección 17, Ciudad 18",
                            Asiento = "Asiento 86",
                            CodigoQR = "ced23063-e19d-462c-84f6-67ab49a05465",
                            Description = "Descripción del partido 17",
                            EventDate = new DateTime(2025, 4, 29, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4094),
                            Fila = "Fila 1",
                            GameName = "Partido 17: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Dirección 18, Ciudad 21",
                            Asiento = "Asiento 83",
                            CodigoQR = "731a8c31-9e84-48aa-8642-231bb1ade3fd",
                            Description = "Descripción del partido 18",
                            EventDate = new DateTime(2025, 3, 31, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4101),
                            Fila = "Fila 28",
                            GameName = "Partido 18: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 4"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Dirección 19, Ciudad 99",
                            Asiento = "Asiento 62",
                            CodigoQR = "b355516d-0ca9-4665-abaf-4bbb7648d826",
                            Description = "Descripción del partido 19",
                            EventDate = new DateTime(2025, 5, 1, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4108),
                            Fila = "Fila 39",
                            GameName = "Partido 19: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 1"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Dirección 20, Ciudad 94",
                            Asiento = "Asiento 79",
                            CodigoQR = "3e40de89-91d0-4a5d-a8c0-7a371f3caf07",
                            Description = "Descripción del partido 20",
                            EventDate = new DateTime(2025, 3, 26, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4114),
                            Fila = "Fila 14",
                            GameName = "Partido 20: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Dirección 21, Ciudad 59",
                            Asiento = "Asiento 99",
                            CodigoQR = "7e4cf79d-f3d0-4b86-a798-61119d86dc99",
                            Description = "Descripción del partido 21",
                            EventDate = new DateTime(2025, 7, 19, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4121),
                            Fila = "Fila 7",
                            GameName = "Partido 21: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Dirección 22, Ciudad 91",
                            Asiento = "Asiento 77",
                            CodigoQR = "f5f01f96-9b63-4538-a2c4-44091f6191c8",
                            Description = "Descripción del partido 22",
                            EventDate = new DateTime(2025, 3, 18, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4127),
                            Fila = "Fila 9",
                            GameName = "Partido 22: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Dirección 23, Ciudad 59",
                            Asiento = "Asiento 69",
                            CodigoQR = "93a7e783-b77b-4889-a129-cc7036d1877b",
                            Description = "Descripción del partido 23",
                            EventDate = new DateTime(2025, 1, 19, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4137),
                            Fila = "Fila 2",
                            GameName = "Partido 23: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Dirección 24, Ciudad 15",
                            Asiento = "Asiento 8",
                            CodigoQR = "bafbb4ff-a007-47b5-a94a-100654ffbcee",
                            Description = "Descripción del partido 24",
                            EventDate = new DateTime(2025, 1, 11, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4143),
                            Fila = "Fila 25",
                            GameName = "Partido 24: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Dirección 25, Ciudad 67",
                            Asiento = "Asiento 95",
                            CodigoQR = "b927429c-c515-488e-8864-f28a8de2c5a8",
                            Description = "Descripción del partido 25",
                            EventDate = new DateTime(2024, 10, 5, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4150),
                            Fila = "Fila 31",
                            GameName = "Partido 25: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 26,
                            Address = "Dirección 26, Ciudad 69",
                            Asiento = "Asiento 29",
                            CodigoQR = "23022115-ba73-4ea2-954b-945141c1a084",
                            Description = "Descripción del partido 26",
                            EventDate = new DateTime(2025, 3, 5, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4156),
                            Fila = "Fila 6",
                            GameName = "Partido 26: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Dirección 27, Ciudad 9",
                            Asiento = "Asiento 43",
                            CodigoQR = "e3b9e12b-f5de-4aea-a08c-92f803e79187",
                            Description = "Descripción del partido 27",
                            EventDate = new DateTime(2024, 12, 3, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4163),
                            Fila = "Fila 23",
                            GameName = "Partido 27: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 28,
                            Address = "Dirección 28, Ciudad 31",
                            Asiento = "Asiento 89",
                            CodigoQR = "0af9e26a-245c-45bf-8ef3-f9ecc7435183",
                            Description = "Descripción del partido 28",
                            EventDate = new DateTime(2025, 4, 28, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4169),
                            Fila = "Fila 19",
                            GameName = "Partido 28: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 29,
                            Address = "Dirección 29, Ciudad 61",
                            Asiento = "Asiento 92",
                            CodigoQR = "b2711092-a3d6-48b5-a619-1b3b0e64ee08",
                            Description = "Descripción del partido 29",
                            EventDate = new DateTime(2025, 2, 11, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4175),
                            Fila = "Fila 37",
                            GameName = "Partido 29: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Dirección 30, Ciudad 75",
                            Asiento = "Asiento 20",
                            CodigoQR = "3f139623-f80a-44d5-a5f6-d396ee86cdff",
                            Description = "Descripción del partido 30",
                            EventDate = new DateTime(2025, 1, 6, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4212),
                            Fila = "Fila 47",
                            GameName = "Partido 30: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 31,
                            Address = "Dirección 31, Ciudad 97",
                            Asiento = "Asiento 89",
                            CodigoQR = "f7fddd98-8acb-46da-95dc-37b6c536e2dc",
                            Description = "Descripción del partido 31",
                            EventDate = new DateTime(2025, 2, 4, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4221),
                            Fila = "Fila 49",
                            GameName = "Partido 31: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 32,
                            Address = "Dirección 32, Ciudad 87",
                            Asiento = "Asiento 45",
                            CodigoQR = "15cbfde3-3803-464e-ba84-068e7f9e8745",
                            Description = "Descripción del partido 32",
                            EventDate = new DateTime(2025, 5, 24, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4228),
                            Fila = "Fila 32",
                            GameName = "Partido 32: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Dirección 33, Ciudad 9",
                            Asiento = "Asiento 54",
                            CodigoQR = "ddc55996-6312-45ca-bfb3-320403e456d1",
                            Description = "Descripción del partido 33",
                            EventDate = new DateTime(2024, 10, 6, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4234),
                            Fila = "Fila 40",
                            GameName = "Partido 33: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 34,
                            Address = "Dirección 34, Ciudad 28",
                            Asiento = "Asiento 70",
                            CodigoQR = "dec098e7-4a7d-438e-b136-a9403e339a2c",
                            Description = "Descripción del partido 34",
                            EventDate = new DateTime(2025, 9, 27, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4241),
                            Fila = "Fila 29",
                            GameName = "Partido 34: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 35,
                            Address = "Dirección 35, Ciudad 3",
                            Asiento = "Asiento 85",
                            CodigoQR = "2db8b111-6178-4bd0-81d4-0849454b8818",
                            Description = "Descripción del partido 35",
                            EventDate = new DateTime(2025, 9, 4, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4248),
                            Fila = "Fila 5",
                            GameName = "Partido 35: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 36,
                            Address = "Dirección 36, Ciudad 50",
                            Asiento = "Asiento 42",
                            CodigoQR = "a2cb1e33-8425-4848-90f6-23e1400f64a1",
                            Description = "Descripción del partido 36",
                            EventDate = new DateTime(2024, 11, 27, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4254),
                            Fila = "Fila 43",
                            GameName = "Partido 36: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 37,
                            Address = "Dirección 37, Ciudad 74",
                            Asiento = "Asiento 84",
                            CodigoQR = "eeeb2d3a-429d-4713-8635-84147c757ce8",
                            Description = "Descripción del partido 37",
                            EventDate = new DateTime(2025, 6, 27, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4261),
                            Fila = "Fila 7",
                            GameName = "Partido 37: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 38,
                            Address = "Dirección 38, Ciudad 31",
                            Asiento = "Asiento 83",
                            CodigoQR = "c1defc14-70a6-4992-8829-160a085552ff",
                            Description = "Descripción del partido 38",
                            EventDate = new DateTime(2025, 7, 25, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4267),
                            Fila = "Fila 41",
                            GameName = "Partido 38: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 39,
                            Address = "Dirección 39, Ciudad 66",
                            Asiento = "Asiento 7",
                            CodigoQR = "1d5d7240-d00c-4f43-a4dc-f777e45b76c9",
                            Description = "Descripción del partido 39",
                            EventDate = new DateTime(2025, 7, 23, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4276),
                            Fila = "Fila 48",
                            GameName = "Partido 39: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 40,
                            Address = "Dirección 40, Ciudad 83",
                            Asiento = "Asiento 97",
                            CodigoQR = "e7083f73-fc1b-4686-8ba3-7a431456cf60",
                            Description = "Descripción del partido 40",
                            EventDate = new DateTime(2025, 7, 7, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4282),
                            Fila = "Fila 42",
                            GameName = "Partido 40: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 41,
                            Address = "Dirección 41, Ciudad 44",
                            Asiento = "Asiento 98",
                            CodigoQR = "563b2cc6-9a9b-478a-8f2e-d59306c64c3e",
                            Description = "Descripción del partido 41",
                            EventDate = new DateTime(2025, 4, 26, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4289),
                            Fila = "Fila 11",
                            GameName = "Partido 41: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 1"
                        },
                        new
                        {
                            Id = 42,
                            Address = "Dirección 42, Ciudad 95",
                            Asiento = "Asiento 65",
                            CodigoQR = "dc198376-10d2-4b5d-aea1-a9c09ba734ef",
                            Description = "Descripción del partido 42",
                            EventDate = new DateTime(2025, 7, 3, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4295),
                            Fila = "Fila 31",
                            GameName = "Partido 42: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 43,
                            Address = "Dirección 43, Ciudad 47",
                            Asiento = "Asiento 4",
                            CodigoQR = "3d19c31c-dd1e-4f3f-afcd-ed944603fd67",
                            Description = "Descripción del partido 43",
                            EventDate = new DateTime(2025, 7, 6, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4302),
                            Fila = "Fila 22",
                            GameName = "Partido 43: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 44,
                            Address = "Dirección 44, Ciudad 68",
                            Asiento = "Asiento 54",
                            CodigoQR = "7ecd3b4a-a20b-449e-84f5-655b51e90567",
                            Description = "Descripción del partido 44",
                            EventDate = new DateTime(2025, 9, 23, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4309),
                            Fila = "Fila 38",
                            GameName = "Partido 44: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 45,
                            Address = "Dirección 45, Ciudad 33",
                            Asiento = "Asiento 1",
                            CodigoQR = "73c36a44-7566-4947-a52d-3d57cf0c2386",
                            Description = "Descripción del partido 45",
                            EventDate = new DateTime(2025, 2, 9, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4333),
                            Fila = "Fila 4",
                            GameName = "Partido 45: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 46,
                            Address = "Dirección 46, Ciudad 75",
                            Asiento = "Asiento 54",
                            CodigoQR = "4908473c-3250-4c19-b36f-061acf195560",
                            Description = "Descripción del partido 46",
                            EventDate = new DateTime(2025, 3, 6, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4340),
                            Fila = "Fila 11",
                            GameName = "Partido 46: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 1"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Dirección 47, Ciudad 50",
                            Asiento = "Asiento 13",
                            CodigoQR = "01767946-5e56-4c08-89ea-21e62e8927f7",
                            Description = "Descripción del partido 47",
                            EventDate = new DateTime(2025, 8, 11, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4349),
                            Fila = "Fila 42",
                            GameName = "Partido 47: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 1"
                        },
                        new
                        {
                            Id = 48,
                            Address = "Dirección 48, Ciudad 97",
                            Asiento = "Asiento 82",
                            CodigoQR = "bd81bf8f-3bdd-4627-968a-e0a27c1192ef",
                            Description = "Descripción del partido 48",
                            EventDate = new DateTime(2025, 1, 7, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4355),
                            Fila = "Fila 25",
                            GameName = "Partido 48: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 1"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Dirección 49, Ciudad 40",
                            Asiento = "Asiento 61",
                            CodigoQR = "430bf443-c2e4-4680-a610-d62b3155b7fd",
                            Description = "Descripción del partido 49",
                            EventDate = new DateTime(2025, 5, 20, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4361),
                            Fila = "Fila 6",
                            GameName = "Partido 49: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 50,
                            Address = "Dirección 50, Ciudad 79",
                            Asiento = "Asiento 42",
                            CodigoQR = "7dd18192-b1d3-4710-9424-ebe940e3f5b7",
                            Description = "Descripción del partido 50",
                            EventDate = new DateTime(2024, 10, 11, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4368),
                            Fila = "Fila 39",
                            GameName = "Partido 50: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 51,
                            Address = "Dirección 51, Ciudad 85",
                            Asiento = "Asiento 35",
                            CodigoQR = "bc6f089a-2d45-46c0-b10f-8fa244807676",
                            Description = "Descripción del partido 51",
                            EventDate = new DateTime(2024, 10, 7, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4374),
                            Fila = "Fila 9",
                            GameName = "Partido 51: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 4"
                        },
                        new
                        {
                            Id = 52,
                            Address = "Dirección 52, Ciudad 79",
                            Asiento = "Asiento 38",
                            CodigoQR = "4b751cf7-7c7d-401c-9147-bef8429fe9d0",
                            Description = "Descripción del partido 52",
                            EventDate = new DateTime(2025, 3, 10, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4380),
                            Fila = "Fila 18",
                            GameName = "Partido 52: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 53,
                            Address = "Dirección 53, Ciudad 68",
                            Asiento = "Asiento 89",
                            CodigoQR = "9da5d062-d830-4abb-a582-700672caf7a6",
                            Description = "Descripción del partido 53",
                            EventDate = new DateTime(2024, 10, 4, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4387),
                            Fila = "Fila 44",
                            GameName = "Partido 53: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 54,
                            Address = "Dirección 54, Ciudad 43",
                            Asiento = "Asiento 8",
                            CodigoQR = "7b8cde40-d059-449a-bd46-a98782d780c8",
                            Description = "Descripción del partido 54",
                            EventDate = new DateTime(2025, 6, 29, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4393),
                            Fila = "Fila 4",
                            GameName = "Partido 54: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 55,
                            Address = "Dirección 55, Ciudad 51",
                            Asiento = "Asiento 72",
                            CodigoQR = "65a1251c-0cfb-4c6c-9e26-b344447a029c",
                            Description = "Descripción del partido 55",
                            EventDate = new DateTime(2025, 4, 6, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4402),
                            Fila = "Fila 15",
                            GameName = "Partido 55: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 56,
                            Address = "Dirección 56, Ciudad 64",
                            Asiento = "Asiento 46",
                            CodigoQR = "1d8a8b0b-6a84-4136-8168-50c848091cf9",
                            Description = "Descripción del partido 56",
                            EventDate = new DateTime(2025, 3, 28, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4408),
                            Fila = "Fila 22",
                            GameName = "Partido 56: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 1"
                        },
                        new
                        {
                            Id = 57,
                            Address = "Dirección 57, Ciudad 70",
                            Asiento = "Asiento 16",
                            CodigoQR = "0cdfe944-d1d2-43b0-89d5-7b6ed432324a",
                            Description = "Descripción del partido 57",
                            EventDate = new DateTime(2024, 11, 23, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4415),
                            Fila = "Fila 26",
                            GameName = "Partido 57: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Dirección 58, Ciudad 11",
                            Asiento = "Asiento 14",
                            CodigoQR = "4e579452-207a-46fa-9c5f-2f21cc6a8a4d",
                            Description = "Descripción del partido 58",
                            EventDate = new DateTime(2025, 9, 20, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4421),
                            Fila = "Fila 44",
                            GameName = "Partido 58: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Dirección 59, Ciudad 54",
                            Asiento = "Asiento 27",
                            CodigoQR = "5f7cc7ad-5002-4268-890f-c35c8babb784",
                            Description = "Descripción del partido 59",
                            EventDate = new DateTime(2025, 7, 13, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4481),
                            Fila = "Fila 13",
                            GameName = "Partido 59: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 60,
                            Address = "Dirección 60, Ciudad 29",
                            Asiento = "Asiento 84",
                            CodigoQR = "35aabd28-6712-4d5e-b961-039434138714",
                            Description = "Descripción del partido 60",
                            EventDate = new DateTime(2025, 8, 13, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4488),
                            Fila = "Fila 10",
                            GameName = "Partido 60: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 61,
                            Address = "Dirección 61, Ciudad 90",
                            Asiento = "Asiento 86",
                            CodigoQR = "dd5190c5-9ba9-4ffd-88a1-6412609d4e0a",
                            Description = "Descripción del partido 61",
                            EventDate = new DateTime(2024, 12, 25, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4494),
                            Fila = "Fila 25",
                            GameName = "Partido 61: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 62,
                            Address = "Dirección 62, Ciudad 56",
                            Asiento = "Asiento 34",
                            CodigoQR = "2044c921-2a14-4773-aca7-1e9790db557b",
                            Description = "Descripción del partido 62",
                            EventDate = new DateTime(2024, 11, 15, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4501),
                            Fila = "Fila 15",
                            GameName = "Partido 62: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 63,
                            Address = "Dirección 63, Ciudad 66",
                            Asiento = "Asiento 19",
                            CodigoQR = "1112945f-0b4f-4bf8-977c-4db004e62474",
                            Description = "Descripción del partido 63",
                            EventDate = new DateTime(2024, 10, 8, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4509),
                            Fila = "Fila 33",
                            GameName = "Partido 63: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 64,
                            Address = "Dirección 64, Ciudad 60",
                            Asiento = "Asiento 49",
                            CodigoQR = "8915077d-8377-40a9-8fc2-0ea7a684d1e9",
                            Description = "Descripción del partido 64",
                            EventDate = new DateTime(2025, 2, 1, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4516),
                            Fila = "Fila 18",
                            GameName = "Partido 64: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 65,
                            Address = "Dirección 65, Ciudad 87",
                            Asiento = "Asiento 55",
                            CodigoQR = "4432aef8-5bdf-462c-901f-caf482e89d51",
                            Description = "Descripción del partido 65",
                            EventDate = new DateTime(2025, 5, 13, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4523),
                            Fila = "Fila 14",
                            GameName = "Partido 65: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 66,
                            Address = "Dirección 66, Ciudad 13",
                            Asiento = "Asiento 42",
                            CodigoQR = "d0b28c3a-3f55-436a-a283-cdfb7ebaa7ca",
                            Description = "Descripción del partido 66",
                            EventDate = new DateTime(2024, 11, 22, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4529),
                            Fila = "Fila 5",
                            GameName = "Partido 66: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 67,
                            Address = "Dirección 67, Ciudad 50",
                            Asiento = "Asiento 95",
                            CodigoQR = "b1113d8c-5495-4871-ab8e-85795522e69b",
                            Description = "Descripción del partido 67",
                            EventDate = new DateTime(2025, 4, 13, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4536),
                            Fila = "Fila 13",
                            GameName = "Partido 67: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 68,
                            Address = "Dirección 68, Ciudad 67",
                            Asiento = "Asiento 80",
                            CodigoQR = "c7b2d6f6-010e-40b9-977a-e8c7e83d8f3e",
                            Description = "Descripción del partido 68",
                            EventDate = new DateTime(2025, 2, 26, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4542),
                            Fila = "Fila 46",
                            GameName = "Partido 68: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 69,
                            Address = "Dirección 69, Ciudad 7",
                            Asiento = "Asiento 6",
                            CodigoQR = "f1601ccd-af7d-4269-98a5-2a010f9a6352",
                            Description = "Descripción del partido 69",
                            EventDate = new DateTime(2025, 1, 15, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4549),
                            Fila = "Fila 20",
                            GameName = "Partido 69: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 70,
                            Address = "Dirección 70, Ciudad 67",
                            Asiento = "Asiento 58",
                            CodigoQR = "d2372873-4684-4087-8505-cc8fe3a19df0",
                            Description = "Descripción del partido 70",
                            EventDate = new DateTime(2024, 10, 4, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4555),
                            Fila = "Fila 22",
                            GameName = "Partido 70: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 71,
                            Address = "Dirección 71, Ciudad 22",
                            Asiento = "Asiento 56",
                            CodigoQR = "f45b9095-e2af-46c6-af54-2ccee1e2570a",
                            Description = "Descripción del partido 71",
                            EventDate = new DateTime(2025, 7, 28, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4564),
                            Fila = "Fila 10",
                            GameName = "Partido 71: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 72,
                            Address = "Dirección 72, Ciudad 13",
                            Asiento = "Asiento 6",
                            CodigoQR = "8cf6f515-1813-4c6a-a782-e1750ed20bb3",
                            Description = "Descripción del partido 72",
                            EventDate = new DateTime(2024, 10, 7, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4570),
                            Fila = "Fila 23",
                            GameName = "Partido 72: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 73,
                            Address = "Dirección 73, Ciudad 82",
                            Asiento = "Asiento 87",
                            CodigoQR = "29d55721-1a08-42b1-adbf-c0c5cfe75e8f",
                            Description = "Descripción del partido 73",
                            EventDate = new DateTime(2025, 7, 26, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4577),
                            Fila = "Fila 44",
                            GameName = "Partido 73: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 74,
                            Address = "Dirección 74, Ciudad 55",
                            Asiento = "Asiento 71",
                            CodigoQR = "07a85820-8d12-458a-8886-045ba4df5a9f",
                            Description = "Descripción del partido 74",
                            EventDate = new DateTime(2025, 9, 10, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4623),
                            Fila = "Fila 43",
                            GameName = "Partido 74: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 4"
                        },
                        new
                        {
                            Id = 75,
                            Address = "Dirección 75, Ciudad 11",
                            Asiento = "Asiento 23",
                            CodigoQR = "bc5ff99e-fec4-4103-83c3-26ee7455781c",
                            Description = "Descripción del partido 75",
                            EventDate = new DateTime(2024, 12, 27, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4630),
                            Fila = "Fila 5",
                            GameName = "Partido 75: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 76,
                            Address = "Dirección 76, Ciudad 54",
                            Asiento = "Asiento 52",
                            CodigoQR = "d33afbd7-c4d8-4614-90bc-c94b8c04804f",
                            Description = "Descripción del partido 76",
                            EventDate = new DateTime(2024, 11, 11, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4636),
                            Fila = "Fila 11",
                            GameName = "Partido 76: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 77,
                            Address = "Dirección 77, Ciudad 71",
                            Asiento = "Asiento 86",
                            CodigoQR = "3309ddcf-2930-4aae-bd69-a3329a0e371b",
                            Description = "Descripción del partido 77",
                            EventDate = new DateTime(2025, 8, 2, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4643),
                            Fila = "Fila 23",
                            GameName = "Partido 77: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 78,
                            Address = "Dirección 78, Ciudad 89",
                            Asiento = "Asiento 19",
                            CodigoQR = "1e9e6a74-4793-4a7a-9417-668cad20a316",
                            Description = "Descripción del partido 78",
                            EventDate = new DateTime(2024, 11, 16, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4649),
                            Fila = "Fila 10",
                            GameName = "Partido 78: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 79,
                            Address = "Dirección 79, Ciudad 76",
                            Asiento = "Asiento 39",
                            CodigoQR = "6fb32346-5dd7-4e43-a615-79e87fff1f30",
                            Description = "Descripción del partido 79",
                            EventDate = new DateTime(2025, 8, 9, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4658),
                            Fila = "Fila 7",
                            GameName = "Partido 79: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 80,
                            Address = "Dirección 80, Ciudad 23",
                            Asiento = "Asiento 14",
                            CodigoQR = "58bbe008-1037-4239-9ee9-6accf5b86573",
                            Description = "Descripción del partido 80",
                            EventDate = new DateTime(2024, 12, 3, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4664),
                            Fila = "Fila 22",
                            GameName = "Partido 80: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 81,
                            Address = "Dirección 81, Ciudad 88",
                            Asiento = "Asiento 94",
                            CodigoQR = "a6ac7b30-3ae3-46c1-bb0d-b1d7aea9e2ad",
                            Description = "Descripción del partido 81",
                            EventDate = new DateTime(2024, 11, 16, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4671),
                            Fila = "Fila 35",
                            GameName = "Partido 81: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 82,
                            Address = "Dirección 82, Ciudad 48",
                            Asiento = "Asiento 56",
                            CodigoQR = "306817d3-08cf-46d0-b4fb-2365eaa83ea0",
                            Description = "Descripción del partido 82",
                            EventDate = new DateTime(2025, 3, 12, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4677),
                            Fila = "Fila 34",
                            GameName = "Partido 82: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 83,
                            Address = "Dirección 83, Ciudad 60",
                            Asiento = "Asiento 42",
                            CodigoQR = "52e6b6da-656e-4cab-9cf8-15b8c28502be",
                            Description = "Descripción del partido 83",
                            EventDate = new DateTime(2025, 4, 10, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4683),
                            Fila = "Fila 45",
                            GameName = "Partido 83: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 5"
                        },
                        new
                        {
                            Id = 84,
                            Address = "Dirección 84, Ciudad 89",
                            Asiento = "Asiento 18",
                            CodigoQR = "1d34d987-1fcc-471f-a808-dec7821d64c7",
                            Description = "Descripción del partido 84",
                            EventDate = new DateTime(2025, 4, 29, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4690),
                            Fila = "Fila 33",
                            GameName = "Partido 84: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 85,
                            Address = "Dirección 85, Ciudad 84",
                            Asiento = "Asiento 26",
                            CodigoQR = "1350bb69-afe6-430c-9535-fbd0a8171b80",
                            Description = "Descripción del partido 85",
                            EventDate = new DateTime(2025, 5, 1, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4696),
                            Fila = "Fila 26",
                            GameName = "Partido 85: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 86,
                            Address = "Dirección 86, Ciudad 75",
                            Asiento = "Asiento 55",
                            CodigoQR = "94e45c32-cd84-4413-8a7c-1b48453f23a6",
                            Description = "Descripción del partido 86",
                            EventDate = new DateTime(2024, 11, 2, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4703),
                            Fila = "Fila 16",
                            GameName = "Partido 86: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 3"
                        },
                        new
                        {
                            Id = 87,
                            Address = "Dirección 87, Ciudad 1",
                            Asiento = "Asiento 84",
                            CodigoQR = "9ab4511b-a6e4-467d-877b-989566648330",
                            Description = "Descripción del partido 87",
                            EventDate = new DateTime(2024, 10, 21, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4711),
                            Fila = "Fila 9",
                            GameName = "Partido 87: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 88,
                            Address = "Dirección 88, Ciudad 92",
                            Asiento = "Asiento 48",
                            CodigoQR = "4d7cb8d3-a4f4-45f3-b02c-70bb525562b6",
                            Description = "Descripción del partido 88",
                            EventDate = new DateTime(2025, 7, 23, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4745),
                            Fila = "Fila 44",
                            GameName = "Partido 88: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 89,
                            Address = "Dirección 89, Ciudad 64",
                            Asiento = "Asiento 49",
                            CodigoQR = "95416010-4992-4250-9d16-8ec3eefa5a4f",
                            Description = "Descripción del partido 89",
                            EventDate = new DateTime(2025, 5, 8, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4752),
                            Fila = "Fila 18",
                            GameName = "Partido 89: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 90,
                            Address = "Dirección 90, Ciudad 15",
                            Asiento = "Asiento 5",
                            CodigoQR = "2d263bc8-6a15-42c5-b29b-b00bc0ee69df",
                            Description = "Descripción del partido 90",
                            EventDate = new DateTime(2025, 4, 6, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4759),
                            Fila = "Fila 6",
                            GameName = "Partido 90: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 1"
                        },
                        new
                        {
                            Id = 91,
                            Address = "Dirección 91, Ciudad 36",
                            Asiento = "Asiento 60",
                            CodigoQR = "fe2f0140-3bce-4009-80b7-92fc7af11b70",
                            Description = "Descripción del partido 91",
                            EventDate = new DateTime(2025, 7, 20, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4765),
                            Fila = "Fila 38",
                            GameName = "Partido 91: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 8"
                        },
                        new
                        {
                            Id = 92,
                            Address = "Dirección 92, Ciudad 19",
                            Asiento = "Asiento 65",
                            CodigoQR = "dd9ec32d-785d-4265-830d-d99eeb96c551",
                            Description = "Descripción del partido 92",
                            EventDate = new DateTime(2025, 7, 14, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4772),
                            Fila = "Fila 49",
                            GameName = "Partido 92: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 93,
                            Address = "Dirección 93, Ciudad 55",
                            Asiento = "Asiento 2",
                            CodigoQR = "e8414f98-204d-48b5-9518-325e5890440b",
                            Description = "Descripción del partido 93",
                            EventDate = new DateTime(2025, 2, 8, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4778),
                            Fila = "Fila 48",
                            GameName = "Partido 93: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 2"
                        },
                        new
                        {
                            Id = 94,
                            Address = "Dirección 94, Ciudad 44",
                            Asiento = "Asiento 31",
                            CodigoQR = "b1a0919b-2d15-4ba9-a6cf-51960b846088",
                            Description = "Descripción del partido 94",
                            EventDate = new DateTime(2025, 8, 4, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4784),
                            Fila = "Fila 26",
                            GameName = "Partido 94: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 95,
                            Address = "Dirección 95, Ciudad 47",
                            Asiento = "Asiento 15",
                            CodigoQR = "e80f2bbd-fccc-46bb-9c1f-4fe315784632",
                            Description = "Descripción del partido 95",
                            EventDate = new DateTime(2024, 12, 10, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4793),
                            Fila = "Fila 42",
                            GameName = "Partido 95: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 9"
                        },
                        new
                        {
                            Id = 96,
                            Address = "Dirección 96, Ciudad 16",
                            Asiento = "Asiento 50",
                            CodigoQR = "71be4aa6-8ca2-4631-bbd8-64ce3774e8fe",
                            Description = "Descripción del partido 96",
                            EventDate = new DateTime(2025, 5, 5, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4799),
                            Fila = "Fila 13",
                            GameName = "Partido 96: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 97,
                            Address = "Dirección 97, Ciudad 34",
                            Asiento = "Asiento 43",
                            CodigoQR = "e0b18b63-8acb-4bc3-97b9-735f952ad55b",
                            Description = "Descripción del partido 97",
                            EventDate = new DateTime(2025, 8, 22, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4806),
                            Fila = "Fila 30",
                            GameName = "Partido 97: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 6"
                        },
                        new
                        {
                            Id = 98,
                            Address = "Dirección 98, Ciudad 71",
                            Asiento = "Asiento 39",
                            CodigoQR = "dfb6627e-b049-4178-b51b-ef65d262773b",
                            Description = "Descripción del partido 98",
                            EventDate = new DateTime(2024, 11, 24, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4812),
                            Fila = "Fila 43",
                            GameName = "Partido 98: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        },
                        new
                        {
                            Id = 99,
                            Address = "Dirección 99, Ciudad 13",
                            Asiento = "Asiento 47",
                            CodigoQR = "7a2b11da-da1a-4f43-b842-54e2deb72569",
                            Description = "Descripción del partido 99",
                            EventDate = new DateTime(2025, 4, 9, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4818),
                            Fila = "Fila 27",
                            GameName = "Partido 99: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 1"
                        },
                        new
                        {
                            Id = 100,
                            Address = "Dirección 100, Ciudad 22",
                            Asiento = "Asiento 82",
                            CodigoQR = "97a59f9c-c864-43b8-85be-d178ec466fe7",
                            Description = "Descripción del partido 100",
                            EventDate = new DateTime(2025, 3, 8, 14, 56, 16, 343, DateTimeKind.Utc).AddTicks(4826),
                            Fila = "Fila 32",
                            GameName = "Partido 100: Equipo A vs Equipo B",
                            Image = "https://media.airedesantafe.com.ar/p/1104be57d6bbde5daa49a8111ee3c158/adjuntos/268/imagenes/003/840/0003840291/1200x0/smart/argentina-espanapng.png",
                            Puerta = "Puerta 7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
